# Generated by Django 4.2.3 on 2023-07-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Jobs TiTle')),
                ('description', models.TextField(verbose_name='Job Description')),
                ('currency', models.CharField(max_length=10, verbose_name='Specify the Currency')),
                ('budget', models.CharField(max_length=10, verbose_name='Budget')),
                ('data', models.DateTimeField(verbose_name='Publishing Data')),
            ],
        ),
    ]
