# Generated by Django 4.2.3 on 2023-07-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('designe', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('link', models.CharField(max_length=100, verbose_name='link')),
                ('phone', models.IntegerField(verbose_name='mobile')),
                ('mail', models.EmailField(max_length=254, verbose_name='email')),
                ('price', models.CharField(max_length=50, verbose_name='price')),
            ],
        ),
    ]
