# Generated by Django 4.2.3 on 2023-07-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_img', models.ImageField(upload_to='images/')),
                ('profession', models.CharField(choices=[('front_end', 'Front_end'), ('back_end', 'Back_end'), ('full stack', 'Full Stack'), ('gaming', 'Gaming'), ('android', 'Android'), ('ios', 'IOS'), ('qa', 'QA'), ('penetration testing', 'Penetration Testing'), ('typer', 'Typer'), ('translator', 'Translator'), ('it', 'IT'), ('devops', 'DevOps'), ('ux/ui', 'UX/UI'), ('web designer', 'Web Designer'), ('seo', 'SEO'), ('aso', 'ASO'), ('graphic designer', 'Graphic Designer')], max_length=20)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last_name')),
                ('experience', models.CharField(max_length=50, verbose_name='Experience')),
                ('skills', models.TextField(verbose_name='skills')),
                ('cover_letter', models.TextField(verbose_name='Cover_Letter')),
            ],
        ),
    ]
