# Generated by Django 4.2.3 on 2023-07-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelacersProfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='cover_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
