# Generated by Django 4.2.3 on 2023-07-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelacersProfiles', '0002_alter_freelancer_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='profession',
            field=models.CharField(choices=[('front_end', 'Front_end Developer'), ('back_end', 'Back_end Developer'), ('full stack', 'Full Stack Developer'), ('gaming', 'Gaming Developer'), ('android', 'Android Developer'), ('ios', 'IOS Developer'), ('software', 'software Developer'), ('software', 'software Engineer'), ('qa', 'QA'), ('penetration testing', 'Penetration Testing'), ('typer', 'Typer'), ('translator', 'Translator'), ('it', 'IT'), ('devops', 'DevOps'), ('ux/ui', 'UX/UI'), ('web designer', 'Web Designer'), ('seo', 'SEO'), ('aso', 'ASO'), ('graphic designer', 'Graphic Designer')], max_length=20),
        ),
    ]
